# Generated by Django 5.0.1 on 2024-02-06 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TogriSoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soz', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='NotogriSoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soz', models.CharField(max_length=250)),
                ('togriSoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.togrisoz')),
            ],
        ),
    ]
